### ISSUE TITLE
deploy lambda only in region us-east-1

### ISSUE THREAD

**Issue by diogoleal** [omerxx/drone-lambda-plugin#7]
I don't know if it's my mistake, but even if I set the region to us-west-2, the drone-lambda-plugin is trying to create the lambda in the us-east-1 region.

That's the message I get from AWS:

```
latest: Pulling from omerxx/drone-lambda-plugin
Digest: sha256:9bb87d55fb04b0e1b55d35479ac62a4c165366a63cb3b3647ea611b7abc88616
Status: Image is up to date for omerxx/drone-lambda-plugin:latest
ResourceNotFoundException ResourceNotFoundException: Function not found: arn:aws:lambda:us-east-1:MY_ACCOUNT_ID:function:mylambda-7
	status code: 404, request id: 4e50159c-69ce-46f7-8fb3-b4699defc9a2
```

My configuration is this:
 
```
 - name: deploy-lambda
    image: omerxx/drone-lambda-plugin
    pull: true
    settings:
      function_name: mylambda-${DRONE_BUILD_NUMBER}
      s3_bucket: mylambda
      region: us-west-2
      file_name: lambda-dir/mylambda-${DRONE_BUILD_NUMBER}.zip
```
